package com.example.reciperoulette.model

data class Recipe(
    val aggregateLikes: Int? = null,
    val analyzedInstructions: List<AnalyzedInstruction> = emptyList(),
    val cheap: Boolean? = null,
    val cookingMinutes: Int? = null,
    val creditsText: String? = null,
    val cuisines: List<String> = emptyList(),
    val dairyFree: Boolean? = null,
    val diets: List<String> = emptyList(),
    val dishTypes: List<String> = emptyList(),
    val extendedIngredients: List<ExtendedIngredient> = emptyList(),
    val gaps: String? = null,
    val glutenFree: Boolean? = null,
    val healthScore: Int? = null,
    val id: Int? = null,
    val image: String? = null,
    val imageType: String? = null,
    val instructions: String? = null,
    val license: String? = null,
    val lowFodmap: Boolean? = null,
    val occasions: List<String> = emptyList(),
    val originalId: Any? = null,
    val preparationMinutes: Int? = null,
    val pricePerServing: Double? = null,
    val readyInMinutes: Int? = null,
    val servings: Int? = null,
    val sourceName: String? = null,
    val sourceUrl: String? = null,
    val spoonacularScore: Double? = null,
    val spoonacularSourceUrl: String? = null,
    val summary: String? = null,
    val sustainable: Boolean? = null,
    val title: String? = null,
    val vegan: Boolean? = null,
    val vegetarian: Boolean? = null,
    val veryHealthy: Boolean? = null,
    val veryPopular: Boolean? = null,
    val weightWatcherSmartPoints: Int? = null
)